apiVersion: v1
kind: Service
metadata:
  name: {{.Chart.Name}}-svc
  labels:
    app.kubernetes.io/name: {{.Chart.Name}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{.Chart.Version}}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.servicePort | default 80 }}
      targetPort: {{ .Values.containerPort | default 80 }}
      protocol: TCP
      name: http
  selector:
    app: {{.Chart.Name}}
